FROM node:24-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY src ./src

RUN npm install -g pm2

COPY ecosystem.config.js .

EXPOSE 5000

CMD ["pm2-runtime", "ecosystem.config.js"]
