FROM node:22-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY src ./src

RUN npm install -g pm2

COPY ecosystem.config.js .

EXPOSE 5000

CMD ["pm2-runtime", "ecosystem.config.js"]
